server:
  port: 9002
spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://47.103.79.58:3306/blob?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
#  mapper-locations: classpath:/
